### ISSUE TITLE
Application Support/Gifox taking up tens of GB

### ISSUE THREAD

**Issue by adams-family** [Gifox/Tracker#201] opened 2021-08-15 09:45 UTC
I was trying to figure out why I'm running out of disk space and noticed that Application Support/Gifox is taking up 15 GB on my SSD.

Is there a way to purge this folder other than manually finding it and deleting old files?

**Comment by iby** [comment] 2021-09-02 04:17
@adams-family Apologies for going quiet on this. A 2.3.0 update landed last week, amongst other improvements it takes care of recording leftovers which may stay around when manually deleting GIFs. It will take care of any old ones too as well as the new ones. Please give it a go, would love your feedback on this to confirm if the issue is resolved. 

Also, there is a slightly different https://github.com/Gifox/Tracker/issues/174 issue with log file getting out of control. We haven't had much luck tracking it down, if you run into something similar please do let us know! 🙏

**Closed** 2021-09-13 03:36 UTC

**Comment by adams-family** [comment] 2022-02-11 17:28
Hi @iby - sorry for the late response, I'm using v '2.3.0 01' but still, I had 31 GB of data in App Support/Containers. I realized that maybe it's because I deleted my GIFs from Finder, not from Gifox. I'd have one suggestion for that case: could we get a 'Clear all recordings' button sometime in the future? I have tens/hundreds of recording but they live a very short life: record & edit & share - I delete the GIF but usually don't go into Gifox to remove it from the list, as well. Thanks!

**Comment by sergei-lobanov** [comment] 2023-03-23 13:44
сan we reopen this issue? its still aсtual

**Comment by iby** [comment] 2023-05-08 20:12
A quick update to keep everyone in the loop. We just resolved [a duplicate #218 issue](https://github.com/Gifox/Tracker/issues/218#issuecomment-1538974019), please see it for further details:

> In the latest 2.6.1 release we introduced recompression of raw files: now, recordings that 3+ days old will get recompressed in the background. You no longer should run into situations when `Compositions` folders takes up 100+ GB of disk space.
> 
> Please note, this is the initial implementation and once we validate that it's working as expected we will apply the same recompression to all recordings as soon as they are created + will see how else this approach can be improved.
> 
> Please bear in mind, recordings can still result taking a lot of space if not cleaned up periodically. Also, as implied above, recent recordings created within the past 3 days will remain in their original format, which is pretty heavy. So, if you create 50 recordings per day and very disk-space-concious, please consider cleaning them up manually for the time being as suggested in the previous post.
