### ISSUE TITLE
Gifox Freezes After Creating New Folder For Output Files

### ISSUE THREAD

**Issue by mjordan56** [Gifox/Tracker#169] opened 2020-07-24 16:08 UTC
After installing Gifox 2 on my Mac, I run Gifox 2 and get a dialog window asking for an output folder for Gifox 2 files. I clicked on the Select... dropdown button and get a dialog window for selecting an output folder. I clicked on the New Folder button and created a folder named "Gifox." The dialog window is dismissed and at this point, the Gifox 2 app is frozen; the Continue button is unresponsive as well as all of the app menus in the menu bar. I had to force the application to quit then restart. After restarting the app everything appears to be fine.

**Comment by ianbytchek** [comment] 2020-10-15 17:19
Thanks for reporting this and apologies for the late reply. We've seen a few of these reports but couldn't reproduce the issue. "After Creating New Folder" turned out to be the key element, after some extraordinary debugging I was able to find a bug in one of the system's frameworks, which probably was introduced in Catalina. 

Interestingly, this doesn't happen if you do all the same but select an existing folder or even use Enter to "okay" or Esc to "cancel" the new folder panel – happens only when using the mouse to "okay" or "cancel" it.

Will be reporting this to Apple for more comments and this should be fixed in the upcoming 2.2.5 release. Again, massive thanks for the detailed report! 🙏

**Closed** 2020-10-15 17:19 UTC

**Comment by ianbytchek** [comment] 2020-10-23 16:04
Fixed in 2.2.5 Beta.
