### ISSUE TITLE
Gifox energy usage

### ISSUE THREAD

**Issue by JKillian** [gifox/tracker#79] opened 2018-02-21 05:56 UTC
When I look at the battery dropdown on my macbook, it tells me that giffox is using significant battery:

![image](https://user-images.githubusercontent.com/1400151/36465134-c7892650-16a1-11e8-9f81-9750c097e637.png)

Activity monitor doesn't seem to think it's that bad though:

![image](https://user-images.githubusercontent.com/1400151/36465170-f5257eba-16a1-11e8-8dcd-c3eec2a13d3e.png)

Anyways, just wanted to mention this in case there is some battery issue happening (I've noticed my battery seems to be draining pretty quickly). I realize there's a good chance that Gifox is not the issue here, so feel free to close this ticket if it doesn't seem like anything actionable!

**Comment by ianbytchek** [comment] 2018-02-21 09:45
@JKillian thanks for reporting on this! Been discussing this with someone else just yesterday. Same picture. Can you [attach process sample](https://support.omnigroup.com/sample-osx) and any other usage information you think might be relevant?

**Comment by ianbytchek** [comment] 2018-02-21 10:04
@feinstruktur to keep you in the loop. Attaching another [sample](https://github.com/gifox/tracker/files/1743561/Sample.of.Gifox.txt).

**Comment by JKillian** [comment] 2018-02-21 23:42
[Sample attached!](https://github.com/gifox/tracker/files/1746107/GifoxSample.txt) Let me know if there's anything else that would be relevant. My usage patterns are normally to use gifox a couple times a day for a few short (5s or so) gifs.

**Comment by ianbytchek** [comment] 2018-02-22 15:26
@rogierslag saves this day! The issue is apparently linked to it running in discrete graphics mode, even when not capturing or doing anything. I'll look into causes.

P. S. https://gfx.io 👇 Add TLD domain letters into domain name and what do you get?! 😃

![](https://s3-us-west-2.amazonaws.com/static.devmate.com/feedback/com.gifox.gifox/2018/02/22/e336e891768e3220e7ccb7913c4ff3631fa2f4dce43691daad9808f869afd78e/a339ea8e2699fd011bed947fcb214526.png)

**Comment by rogierslag** [comment] 2018-02-22 15:36
@holleboom you might be encountering the same issue!

**Comment by ianbytchek** [comment] 2018-03-08 08:31
Good news and bad news! Good, we've released 1.5.1 a couple of days ago, which addresses potential weak spots, which might cause this. Bad, we don't have a single discrete/dual GPU Mac and cannot properly test this. So, please update, keep an eye on performance and let know if the issue persists? There's also not much details on the Internet, so if anyone know anything, even a hint, please share – would be of great help! 👍

**Comment by rogierslag** [comment] 2018-03-08 09:00
Just a quick check whether this gif recording will trigger discrete gpu. It did not!

**Comment by rogierslag** [comment] 2018-03-08 09:04
Just updated and tested it locally. During the creation of the gif the discrete GPU does not trigger. However when the gif is saved, it does switch the GPU on.

This was the gif used for testing:
![2018-03-08 10 00 15](https://user-images.githubusercontent.com/2778689/37142178-9c85386e-22b7-11e8-8720-f180028a29de.gif)

Screenshot of the graphics card
<img width="267" alt="screenshot 2018-03-08 10 02 31" src="https://user-images.githubusercontent.com/2778689/37142267-e1b8fa88-22b7-11e8-91dc-4fb1d2fab74e.png">

Note spotify also manages to leak to the GPU.... (External display always triggers the GPU, so dont worry about that)

**Comment by ianbytchek** [comment] 2018-03-09 11:03
Awesome! I'm gonna close this. If you see any signs of misbehaviour, please let know! 👊

For anyone facing similar issues, this might be related to global mouse and keyboard event observers not being turned off when not needed. Both, CG and NS.

**Comment by rogierslag** [comment] 2018-03-09 12:40
In which version is this fixed then?

**Comment by ianbytchek** [comment] 2018-03-09 16:03
1.5.1. Still behaving good?

**Comment by rogierslag** [comment] 2018-03-09 22:37
No it triggers the GPU once the recording is done. Not during. Maybe during saving or converting? Main pain point is it does not stop using the GPU

**Comment by ianbytchek** [comment] 2018-03-10 08:35
Can you check if the same happens in following cases? Please relaunch it before each test.

1. Start area selection with <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>5</kbd> and select a region. Cancel it with <kbd>Esc</kbd>. Don't record anything.
2. Start window selection with <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>6</kbd> and select a window. Again, cancel, don't record.
3. Same as 1, but carry on and make a recording.

Please keep an eye during each test when discrete GPU kicks in, during selection or during recording? If during selection and during recording, does it let go when selection is cancelled without making a recording?

**Comment by rogierslag** [comment] 2018-03-12 10:49
1. Does not trigger GPU
1. Does not trigger the GPU
1. Does trigger the GPU, but only after the recording ended

![2018-03-12 11 49 26](https://user-images.githubusercontent.com/2778689/37279563-7623f0ca-25eb-11e8-96db-d093757e6dc6.gif)

**Comment by feinstruktur** [comment] 2018-03-12 14:12
I'm also still seeing Gifox appear in the "Energy Shame" menu with 1.5.1 after recordings.

One thing I noticed which may be related:

When I hit Cmd-Shift-6 to to start a window recording it always briefly shows the capture frame and then immediately cancels the action. I need to trigger the key combo a second time for the selector to stay around and to be able to choose a window.

**Comment by ianbytchek** [comment] 2018-03-12 18:09
@rogierslag thanks! We've got a few ideas, I'll come back with more details soon.

@feinstruktur doubt it. Do you happen to have <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>6</kbd> globally configured for any other apps or in your system? Does changing it in preferences to a different combination help?

**Comment by feinstruktur** [comment] 2018-03-15 08:18
@ianbytchek Changing the Gifox shortcut away from Cmd+Shift+6 indeed fixes that.

I've got a Touch Bar MBP and Cmd+Shift+6 takes Touch Bar screenshots, which is incredibly useful 😛. I've got that disabled (can't entirely remove it) but who knows if maybe the system still captures it for some odd reason. That's the only other overlap I can see with Cmd+Shift+6.

Anyway, all good - thanks :)

**Comment by ianbytchek** [comment] 2018-04-02 08:16
Little heads up. My biggest hope was with [NSSupportsAutomaticGraphicsSwitching](https://developer.apple.com/library/content/qa/qa1734/_index.html) trick, but it has zero effect. We've tested several separate components, but didn't find anything causing this on it's own. So, the quest continues.

**Comment by ianbytchek** [comment] 2018-04-07 19:49
Good news! This is fixed and will be available in the upcoming release!

**Comment by rogierslag** [comment] 2018-04-10 06:35
Do you happen to have an ETA when this update will hit the Mac Store?

**Comment by AlexTugarev** [comment] 2018-04-19 11:08
Thanks for notifying @ianbytchek!

**Comment by rogierslag** [comment] 2018-04-24 08:33
Any update on the release date? Working on battery power at a clients makes using Gifox quite difficult as it now uses more energy than Vagrant and IntelliJ combined unfortunately

**Comment by ianbytchek** [comment] 2018-04-24 08:37
Sorry friends, hoped to publish it last week but discovered a few underwater rocks that required extra attention. Finishing testing as we speak. Should be available in a couple of hours. 🤞

**Comment by ianbytchek** [comment] 2018-04-24 20:56
Okay! Direct-download version just been published – update from within the app. App Store and Setapp are under review. To make this bitch go away we've taken encoding into a separate service, which we wanted to do for a while. It triggers the discrete GPU mode (not the main app) and quits after 30 seconds after finishing all work. This is a huge change, so please keep an eye on this and report any issues. Thanks for patience and support!

![2018-04-25 00 48 46](https://user-images.githubusercontent.com/1086845/39213731-62d34ec6-4823-11e8-8210-062138c10d23.gif)

**Closed by ianbytchek** 2018-04-24 20:56 UTC

**Comment by ianbytchek** [comment] 2020-02-12 17:19
Hello friends! If you're already using version 2, could you please check if the issue is happening again? If no, please report here, if yes, please provide details in #135. 👍
