### ISSUE TITLE
[BUG] First click shoudn't be highlighted

### ISSUE THREAD

**Issue by mrleblanc101** [Gifox/Tracker#232] opened 2022-04-01 20:21 UTC
The first time you click, nothing happen because the focus shift from Gifox to the application.
Since the first click is not interactive, it shouldn't trigger the red circle animation.
This is not a bug in the website, when I'm not recording with Gifox, the heart get filled on the first click.
![2022-04-01 16 20 00](https://user-images.githubusercontent.com/17392251/161335806-3a986809-8550-4069-8a39-7eb5f8f43bde.gif)

**Comment by mrleblanc101** [comment] 2022-04-01 20:36
I guess it's a duplicate of #203

**Comment by iby** [comment] 2022-04-03 14:38
Hey @mrleblanc101! Yes, excellent observation and yes, it is a dupe of #203. The best way around this is to use shortcuts, but this is in the pipeline and will be fixed. Gonna close this one, let's track it in #203.

**Closed by iby** 2022-04-03 14:38 UTC
