### ISSUE TITLE
Could not let it work on Sequoia - No way to select target folder

### ISSUE THREAD

**Issue by lpatiny** [gifox/tracker#286] opened 2024-10-07 21:16 UTC
Since my update to Version 15.0 (24A335) GifFox can not save to any folder. It will not remember the folder I select.

Gifox has full access to the disk:

<img width="323" alt="image" src="https://github.com/user-attachments/assets/ab41be84-e6ed-41cc-b5ed-9b4b819d5b60">

Here is what is happening when I try to make a screen capture:

![CleanShot 2024-10-07 at 23 10 00](https://github.com/user-attachments/assets/83792094-506a-4aa1-a41f-77eebd76297d)

I tried to desinstall and reinstall Gifox without success.

**Comment by lerinagalimova** [comment] 2024-10-08 10:40
Hey @lpatiny , thanks for reaching out and reporting this. To help us investigate and understand the problem better, could you please share your [diagnostics data](https://github.com/Gifox/Tracker/assets/1086845/1c160a6d-3527-4bbe-8a56-4a3db351b893) with us?

**Comment by lpatiny** [comment] 2024-10-08 19:27
[Diagnostic Data.zip](https://github.com/user-attachments/files/17298268/Diagnostic.Data.zip)

**Comment by jdaily** [comment] 2024-10-11 12:49
I'm also having this issue on the Pro version from the App Store.

**Comment by iby** [comment] 2024-10-12 06:36
Thanks for reporting this folks. It's a regression on Sequoia, will be fixed in the next release in a couple of days. Apologies for the troubles… 😔

**Comment by iby** [comment] 2024-10-13 14:38
Hello friends! After digging deeper into this, there seems to be bug with macOS 15 Sequoia confirmed by Apple technical support [here](https://forums.developer.apple.com/forums/thread/765433?answerId=807857022#807857022) and [here](https://developer.apple.com/forums/thread/764435?answerId=806097022#806097022):

> What you're hitting is bug in `ScopedBookmarksAgent` which can cause it hang if it happens to have been launched when the keychain was also locked (for example, late in the screen lock process). That bug is fixed as of macOS 15.1 beta 4.

> If you're hitting it regularly during development, you can resolve the issue by killing ScopedBookmarksAgent (you may also need to kill and relaunch your app, depending on what state it ends up). On the user side, a log out (or reboot) should resolve the issue.

So, if this is happening, try the above suggestion:
- Killing `ScopedBookmarksAgent` in [Activity Monitor](https://support.apple.com/en-gb/guide/activity-monitor/actmntr1002/mac), see GIF below.
- Relaunching the app if necessary, close it down with <kbd>Cmd</kbd > + <kbd>Q</kbd> while active or using the [main menu](https://gifox.app/docs/using-gifox#main-menu).
- Alternatively try logging out and in, or rebooting your Mac.

Again, apologies for the troubles, hopefully this gets resolved in the next macOS update – keep an eye on that and check you're running the latest version.

I wasn't able to catch this myself – this is more of a random issue. If you come across it and manage to solve this, would appreciate any tips and hints for other users! 🙏

![2024-10-13 15 35 48](https://github.com/user-attachments/assets/4df26309-724f-4733-9992-5d3f8334bf7a)

**Comment by iby** [comment] 2024-11-12 18:57
@lpatiny @jdaily howdy friends! Was wondering if you had a chance to upgrade to the latest macOS 15.1 and if the issue got fixed in there? Would much appreciate any feedback! 🙏

**Comment by lpatiny** [comment] 2024-11-12 20:50
I just updated and it seems indeed to work correctly. Thanks ! I will tell you if this problem appears again.

**Closed as completed** 2024-11-13 07:20 UTC
