### ISSUE TITLE
Unable To Play GIF Within The Gifox Editor Window

### ISSUE THREAD

**Issue by Sayvai** [Gifox/Tracker#182] opened 2020-11-16 17:18 UTC
Gifox version: `2.2.5`
OS: `macOS Catalina 10.15.7 (19H15)`
Paid member: `Yes`

**Summary**: After successfully recording a GIF, while i then open the Gifox editor window, I am unable to play the GIF within the Gifox editor window, nor any other already recorded / non-edited / edited GIFs.

I had even quit Gifox (`cmd + Q`), but i was still not able to play the recorded GIFs within the Gifox editor. This applies also even after recording any new Gifox GIFs, as not once am i able to play the GIFs.

Finally, i even restarted my macOS, and am at no point able to play the recorded GIF, even after creating one.

Any ideas? 🤔

**Steps to reproduce**:

1. Record a GIF
2. Open up the Gifox editor window against the newly recorded GIF.
3. Click on the Play icon button to play the sequence of frames continuously.

**Expect**: The sequence of GIF frames to play continuously within the main panel of the Gifox editor window.

**Observed**: The sequence of GIF frames does not appear to continuously play within the main panel of the Gifox editor. It just maintains the display of a single static GIF frame.

I attach a GIF (recorded via Gifox 2) below which demonstrates the bug:
![2020-11-16 17 01 09](https://user-images.githubusercontent.com/7581546/99283853-76667e80-282d-11eb-8b8b-37d432285bbc.gif)

**Comment by ianbytchek** [comment] 2020-11-16 18:33
Hey @Sayvai, thank you for the super-detailed report and apologies for the troubles! Yes, there's definitely a regression in the latest build… 🤔 This will be fixed in the upcoming release, in the meantime you can use <kbd>Space</kbd> key to start and pause the playback in the editor.

**Comment by Sayvai** [comment] 2020-11-16 18:58
Brilliant, and thank you for looking into this @ianbytchek 😃

I'll remember to use the `space` key to play and pause the recorded GIF!

**Comment by iby** [comment] 2022-06-18 09:17
Uh-oh… I'm doing some tidying up and looks like I completely forgot about this one. This was addressed in the following up release, must have been 2.3.0 and should be fixed, so I'm going to close this one down. Sorry for going off the radar and not notifying earlier.

P.S. We released yesterday 2.4.2 with lots of improvements and fixes, make sure to not skip that update! ✌️

**Closed by iby** 2022-06-18 09:17 UTC
Labels: bug, frontlog
