### ISSUE TITLE
Problems on macOS 10.15 Catalina 

### ISSUE THREAD

**Issue by iby** [Gifox/Tracker#115] opened 2019-10-09 06:38 UTC
Gifox 1 on macOS Catalina is capturing only desktop background and crashing when trying to capture a window. 

The new macOS introduced new behaviour and features, including strengthened security and privacy protection to prevent apps without explicit access to record your screen, which don't play well together with the original Gifox 1 version. This issue provides solutions for the most common problems.

**Recording problems:** The first issue #114 you're most likely to experience is with the recording itself. To fix it try recording in **free selection mode (not in window selection mode)** to bring up the system security dialogue. Use instructions or go to System Preferences > System Preferences > Security & Privacy > Privacy > Screen Recording and grant Gifox the access. Restart the app as prompted. That's it. It the app doesn't show up in screen recording privacy settings see the related #121 issue that offers workarounds.

**Crashing preferences:** The app crashes after closing certain windows, including preferences, welcome dialogue, quick preferences, etc. This is caused by updated system components and unfortunately there's no way around it apart from ignoring it. Again, this works perfectly fine in all pre-Catalina macOS releases.

[Gifox 2](https://gifox.io) has been recently released packed with improvements and features, including full Catalina compatibility, see [release highlights](https://medium.com/gifox/gifox-2-is-here-release-highlights-bc93e670388d) for full details.

**Comment by ianbytchek** [comment] 2019-10-10 11:54
Gifox 2 Beta [build 5](https://gifox.io/prerelease) has just been published with the above issues resolved. Please update and let know if there are any problems. If you've updated yesterday you'll need to download directly from the website again, sorry. The public stable release is a few days away. Thanks for patience and stay tuned.

**Comment by taras** [comment] 2019-10-10 14:18
@ianbytchek I bought Gifox on AppStore. I don't think I have a license key. How do I use the beta?

**Comment by mcab** [comment] 2019-10-10 20:11
![gifox-privacy-screen-recording](https://user-images.githubusercontent.com/4522043/66602431-f7e5da80-eb5e-11e9-85d2-d7c37018e1ce.gif)

Not sure what's going on here. Clicking on "Authorize Gifox" tries to add it to "Screen Recording," but there's no prompt to add it, nor is there a way to manually add it.

This is on macOS Catalina 10.15 (19A583), using Gifox 2.0.0-beta.5.

**Comment by taras** [comment] 2019-10-10 20:13
@ianbytchek actually, I see the problem now 
<img width="505" alt="image" src="https://user-images.githubusercontent.com/74687/66602807-dc87c900-eb78-11e9-98c9-69cd32c4c3e3.png">

**Comment by ianbytchek** [comment] 2019-10-10 20:27
@mcab Can you try the following in the same order? Close all preferences windows, relaunch Gifox and try again? If that doesn't help and you don't mind, reset all privacy settings with `tccutil reset All` and try again?

@taras Sorry, yes, won't work with App Store / Setapp licences. DM me and I'll share a temporary key.

**Comment by ianbytchek** [comment] 2019-10-10 20:35
@mcab Thinking about this further, the only thing that comes to mind is the privacy warning dialogue did came up and the app was denied access, in which case it would't appear again. Could have this happened? Relaunching the app should solve this, but might need permission reset.

**Comment by mcab** [comment] 2019-10-10 20:40
@ianbytchek I've tried both flows. Closing all preference windows, relaunching Gifox, and trying again doesn't place Gifox into the "Screen Recording" selection area.

Forcefully resetting with `tccutil` and trying to relaunch prompts the user that Gifox would like to record the screen, but then not show up underneath Privacy > Screen Recording.

![force-reset-privacy-settings](https://user-images.githubusercontent.com/4522043/66604654-6e84d700-eb63-11e9-9a85-b7b0b4c04b3e.gif)

**Comment by mcab** [comment] 2019-10-10 22:07
If it helps in debugging, I ran into this problem on Zoom, where sharing your screen directly would prompt Zoom to ask for permissions in System Preference. Going there would not have Zoom underneath "Screen Recording" applications.

What worked was hosting a meeting within Zoom, and then sharing your screen from there. That forced Zoom to try and take control to record the screen, which then prompted the dialogue to check System Preferences for Screen Recording. Afterwards, I could screen record (through screen sharing) in either context. Kind of weird, but 🤷‍♂️.

**Comment by ianbytchek** [comment] 2019-10-11 05:43
That most certainly is not what should be happening and 99.999% chance the problem is with the your macOS itself. Can you try restarting the machine and trying granting the permissions once more just to see if anything resets its brain? Otherwise I can contact Apple support to see if this can be cured. Ideally there would be a way to add the permission manually, but the only thing I can find is [tccutil.py](https://github.com/jacobsalmela/tccutil), which stopped working properly awhile ago.

**Comment by cowboyd** [comment] 2019-10-11 19:32
I've also downloaded Gifox from the App Store and am working on Catalina. Is it fixed there or do we still need a temporary key?

**Comment by hiquest** [comment] 2019-10-12 13:58
hey guys! Kinda same situation here. While I was able to set the permission, now anytime I try to record the screen it asks me to add the permission, even though it's already there! Talking about the beta here.

<img width="1201" alt="Screenshot 2019-10-12 15 57 12" src="https://user-images.githubusercontent.com/227325/66702543-1d164c80-ed09-11e9-933c-1ba17262283c.png">

**Comment by ianbytchek** [comment] 2019-10-12 15:42
@hiquest Very interesting. I've moved this into a separate issue: #116, please see if any of the suggestions help and report there.

**Comment by xvilo** [comment] 2019-10-31 23:02
@ianbytchek same issue here as @mcab has, doing `tccutil reset All` removed ALL premissions.... this is not really what I wanted because I hate the strong policies already. 

<img width="1171" alt="Screenshot 2019-11-01 at 00 00 05" src="https://user-images.githubusercontent.com/390769/67991815-d302f580-fc3a-11e9-90f8-bc94c607c62c.png">

after command:

<img width="662" alt="Screenshot 2019-11-01 at 00 02 15" src="https://user-images.githubusercontent.com/390769/67991834-e2823e80-fc3a-11e9-890f-4ef22e2529bb.png">
<img width="659" alt="Screenshot 2019-11-01 at 00 02 11" src="https://user-images.githubusercontent.com/390769/67991835-e2823e80-fc3a-11e9-8af0-dd8988a398dc.png">

**Comment by ianbytchek** [comment] 2019-11-01 07:15
It's a bummer, sorry @xvilo. The permissions are tracked in the linked #116 with less destructive first steps. I updated the original post with the reference and hid the outdated instructions.

**Comment by mflores-verys** [comment] 2019-11-08 16:11
Are there any plans to release these updates to the Mac App Store version? @ianbytchek

**Comment by ianbytchek** [comment] 2019-12-01 11:07
@mflores-verys sorry, looks like I missed your comment. The new version has been published last week, see [release highlights and upgrading details](https://medium.com/gifox/gifox-2-is-here-release-highlights-bc93e670388d). There might be a problem with upgrading a Mac App Store version, a fix is underway, contact us separately on that if run into any issues!

**Closed** 2023-03-02 20:50 UTC
