### ISSUE TITLE
Gifox throws a grey shade over one of my virtual desktops

### ISSUE THREAD

**Issue by dimitrieh** [gifox/tracker#54] opened 2017-03-29 23:11 UTC
This happens quite often. Have to quit/restart gifox to fix it. Is this a known bug to you?

**Comment by dimitrieh** [comment] 2017-03-29 23:12
also the gifs end up with a shade in them, example:

![2017-03-30 01 06 39](https://cloud.githubusercontent.com/assets/429659/24480664/e84b8108-14e5-11e7-95fd-9b111029bcbe.gif)

**Comment by ianbytchek** [comment] 2017-03-30 14:02
The last release addressed this issue specifically, which was supposed to be fixed in 1.2.7. Are you on that version? We didn't test it with virtual screens, so I just briefly did and couldn't reproduce it, but observed other unexpected behaviour, so will review this for the next release. Can you provide a more detailed description of you setup and how to reproduce? P. S. Cool animations!

**Comment by dimitrieh** [comment] 2017-03-31 13:24
I have this quite often.. perhaps most often i think (but not sure) on apps that are in full screen mode

@ianbytchek i couldn't find out how to see which version of gifox i am using, but according to the mac app store i am on 1.2.7

> Cool animations!

this is from the google design website ;)

**Comment by kevinsimper** [comment] 2017-04-04 21:02
![image](https://cloud.githubusercontent.com/assets/1126497/24678417/ca9f9320-198a-11e7-8753-5ee2580dd173.png)

I am getting this and everything is updated on my App Store

**Comment by ianbytchek** [comment] 2017-04-05 08:18
@kevinsimper can you help me out a little? How many screens? Any virtual screens? Can you pin point exactly when this happens, i.e., after finishing the recording or after cancelling it or at some other point? Does it happen when using Gifox or after some event when it's already hidden? Thanks!

**Comment by kevinsimper** [comment] 2017-04-05 12:23
I have two external monitors and my macbook 15 2016 open. It persist during and after ending recording where I drawed the recording area. It disappears when I close Gifox.

I have recordings that are more grey than the color they should have recorded.

**Comment by kevinsimper** [comment] 2017-04-05 12:24
I just send a gif through the feedback form with a gif that was recorded that had the grey color in. 

The grey color does not always show up.

**Comment by ianbytchek** [comment] 2017-04-05 14:16
Thanks all, that gives some context. Aiming to provide a fix later this or early next week, will keep you posted.

**Comment by dimitrieh** [comment] 2017-04-13 13:48
@ianbytchek would love to see this soon ;) i have to close the application now when i used it and start it up again.. also impacts the quality of my gifs

**Comment by ianbytchek** [comment] 2017-04-16 11:30
The update has been pushed to App Store and under review. We've discovered two weak spots, which could have potentially been causing these issues. I'm concerned that we couldn't reproduce the issue with multiple screens and spaces, thus don't really know if this is fully solved or not. One thought that comes to mind is some other app is interfering with Gifox. Just in case if things don't go smoothly, could you attach a list / screenshot of you accessibility-enabled apps?

Also, I assume this wasn't always like that? If you can think of any new apps or system changes around the point when this all began, it could greatly help solving this. Thanks for support and patience!

![image](https://cloud.githubusercontent.com/assets/1086845/25070802/ef243fca-22b8-11e7-8979-4ea7d5cf95e1.png)

**Comment by ianbytchek** [comment] 2017-04-18 05:24
Update just landed in the App Store, can you confirm if it's better / fixed?

**Comment by dimitrieh** [comment] 2017-04-18 08:19
thanks a lot! It seems to work, if not i will let you know! The only app in the list that jumps out is http://www.quicklensapp.com/

**Closed** 2017-05-11 15:50 UTC
Labels: bug
