### ISSUE TITLE
Record area --> no GIF saved

### ISSUE THREAD

**Issue by crcastle** [gifox/tracker#76] opened 2018-01-15 23:22 UTC
I drag gifox's rectangle over a small area of my screen, hit the play button, do some stuff, then hit stop... but then no GIF appears in gifox's dropdown or my specified save folder (Downloads), and I don't get an error.  See screen recording linked below to see the issue in action.

https://cl.ly/oqlW

Here's my setup.  What else can I provide to help you debug?
![image](https://user-images.githubusercontent.com/275734/34965239-750775d2-fa07-11e7-8014-80c157198e8f.png)
![image](https://user-images.githubusercontent.com/275734/34965211-5003e70c-fa07-11e7-85bc-24b82ad23ab7.png)
![image](https://user-images.githubusercontent.com/275734/34965219-5709a186-fa07-11e7-9d1c-854bd701afc2.png)
![image](https://user-images.githubusercontent.com/275734/34965222-5d9ab6a2-fa07-11e7-9d67-ca9fa66804f8.png)
![image](https://user-images.githubusercontent.com/275734/34965227-66e123e0-fa07-11e7-8f8c-6ad0a459a24f.png)
![image](https://user-images.githubusercontent.com/275734/34965233-6d0de4ba-fa07-11e7-800a-2dbc15b7de93.png)

**Comment by crcastle** [comment] 2018-01-15 23:54
Also gifox decided to have a non-stop thrash party on my CPU right after trying to record this GIF a few times.  Quitting and re-opening fixed it, although I haven't tried to record any more GIFs.

![image](https://user-images.githubusercontent.com/275734/34965864-4277aefc-fa0c-11e7-8574-97509cd986f4.png)

**Comment by ianbytchek** [comment] 2018-01-16 06:25
It seems like you're hitting cancel button, not stop – there was an issue with CPU overuse, fixed in 1.5.0. You should update by the way, it comes with lots of other improvements! Let me know if issue remains?

**Comment by crcastle** [comment] 2018-01-16 22:05
@ianbytchek I'm hitting the square button in the video (and in all my attempts).  Is that cancel or stop?  I assumed X is cancel and square is stop.  Is that incorrect?

**Comment by ianbytchek** [comment] 2018-01-16 22:51
That sounds correct. High CPU was most likely caused by cancelling something earlier – we had a nasty bug, I don't see it on GitHub, but it had affected many. Hmmm, I just double checked and it is a strange issue indeed. As you can see, the GIF gets clearly recorded – progress bar indicates it gets written, so probably something goes wrong when copying it into final destination. Can you re-select output directory or use a different one? I'll look into this further at our end as well, thanks for reporting!

**Comment by crcastle** [comment] 2018-01-16 23:26
Thanks @ianbytchek. Fortunately (for me but probably not you in debugging), upgrading to 1.5.0 resolved the problem.  But let me know if I can do anything else to help you debug.

p.s. I make a lot of animated GIFs in my job and Gifox is by far the best combination of image quality and ease of use!  For comparison, I've used [CloudApp](https://www.getcloudapp.com/), [LICEcap](https://www.cockos.com/licecap/), recording as video and then converting with imagemagick and a few other CLI tools.

**Comment by ianbytchek** [comment] 2018-01-17 07:20
Thanks Chris, will do! Happy when you guys are happy!

**Closed** 2018-03-01 21:01 UTC

**Comment by crstamps2** [comment] 2018-06-25 13:43
I am experiencing this issue still on version 1.6.1

**Comment by ianbytchek** [comment] 2018-06-26 13:30
If this is high-resource consumption related, please open a new issue with details. With 1.6.1 we are having problem #89 while saving the GIF, this will be sorted shortly.

**Comment by ianbytchek** [comment] 2018-06-28 14:53
@crstamps2 just published an update for direct-download version, please have a look and let know if the issue remains?
