### ISSUE TITLE
Speed Multiplier doesn't change speed

### ISSUE THREAD

**Issue by MrErdreich** [gifox/tracker#265] opened 2023-09-14 21:31 UTC
When using the speed multiplier slider, all it seems to do is shorten my clip. So if I multiply the speed by two, it cuts the second half of my clip off but leaves the remaining half the same speed.

**Comment by iby** [comment] 2023-11-09 17:10
@MrErdreich apologies for the lagged reply. I just tested this with the latest 2.6.2 release and it seems to be working as expected:

![2023-11-09 17 02 09](https://github.com/Gifox/Tracker/assets/1086845/687ee4c8-5c81-4a64-9017-b2c44107ca7c)

We have a separate issue #267 related to videos not being fully recorded in macOS 14 Sonoma, which seems to be occurring only on Intel-based Macs.

If you're still running into this issue, could you please provide diagnostics data (can be done by contacting support or attached here):

![diagnostic-data-smaller](https://github.com/Gifox/Tracker/assets/1086845/056d41a5-ec1d-4310-9013-8e4a132ece3d)

**Comment by stdword** [comment] 2024-02-21 21:21
Hello, @iby !
I faced the same problem. Speed always multiplier didn't work. For any gif and exported mp4.
It just shrinks my current clip, but the speed level is 1x.

I can add details:
- it doesn't work when I sliced recorded data on pieces, remove some of them or reorder, otherwise it works
- sometimes speed didn't increased at all and sometimes speed increased, but the ranges of video slices calculated wrong and the end of recording contains black screen after exporting

## Tech details
### System Info

```
System: MacBookAir10,1 Version 13.4 (Build 22F66)
Memory: 256.3 MB (16.0 GB)
Processor: Apple M1: 25.6% (10.2%)
GPU: Apple M1
Display: <"Built-in Retina Display" main: true, scale: 2.0, frame: (0.0, 0.0, 1440.0, 900.0), bounds: (0.0, 0.0, 1440.0, 900.0), color space: "Color LCD colorspace", refresh rate: "60.0 Hz">
Power: <"InternalBattery-0" capacity: 82%, charging: false, charged: false>
```

### Log of latest recording / editing session with this issue
```
2024-02-22 00:14:21.159 [EVENT] Pressed ⌥⌘2 hotkey associated with ToggleScreenRecordingSessionCommand command.
2024-02-22 00:14:21.167 [INFO] Accessing output directory url: /Users/dword/Downloads.
2024-02-22 00:14:21.173 [INFO] Screen recording session changed state: ready → selecting.
2024-02-22 00:14:21.774 [EVENT] Started making new selection.
2024-02-22 00:14:22.695 [EVENT] Finished making new selection: ScreenSelection(mode: area, frame: <x:299 y:698 w:774 h:497>, screen: <main, x:0 y:900 w:1440 h:900>, scale: 2.0, config: none).
2024-02-22 00:14:24.129 [EVENT] Pressed ␣ key captured in Screenware.ScreenSelectorKeyboardManager.
2024-02-22 00:14:24.131 [INFO] ScreenCaptor updating screen link with current state: idle
2024-02-22 00:14:24.135 [INFO] Screen recording session changed state: selecting → recording.
2024-02-22 00:14:24.140 [INFO] Recorder updating state from: ready, to: recording
2024-02-22 00:14:24.142 [INFO] ScreenCaptor starting capturing, current state: idle
2024-02-22 00:14:24.142 [INFO] ScreenCaptor creating screen link for screen id: 1, selection: ScreenSelection(mode: area, frame: <x:299 y:698 w:774 h:497>, screen: <main, x:0 y:900 w:1440 h:900>, scale: 2.0, config: none).
2024-02-22 00:14:24.144 [INFO] CIContext creating with metal device: <AGXG13GDevice: 0x1608a6c00>
    name = Apple M1
2024-02-22 00:14:24.145 [INFO] ScreenLink starting display link…
2024-02-22 00:14:24.145 [INFO] ScreenLink updating state from: idle, to: running
2024-02-22 00:14:24.145 [INFO] ScreenCaptor synchronizing with screen link state from: idle, to: capturing
2024-02-22 00:14:24.146 [INFO] Enabling ⌘S shortcut associated with StopRecordingSessionCommand command.
2024-02-22 00:14:24.164 [INFO] ScreenCaptor health check…
2024-02-22 00:14:24.263 [INFO] Recorder health check…
2024-02-22 00:14:25.181 [INFO] ScreenCaptor health check…
2024-02-22 00:14:25.278 [INFO] Recorder health check…
2024-02-22 00:14:26.181 [INFO] ScreenCaptor health check…
2024-02-22 00:14:26.295 [INFO] Recorder health check…
2024-02-22 00:14:27.197 [INFO] ScreenCaptor health check…
2024-02-22 00:14:27.307 [INFO] Recorder health check…
2024-02-22 00:14:28.214 [INFO] ScreenCaptor health check…
2024-02-22 00:14:28.309 [INFO] Recorder health check…
2024-02-22 00:14:29.230 [INFO] ScreenCaptor health check…
2024-02-22 00:14:29.327 [INFO] Recorder health check…
2024-02-22 00:14:30.230 [INFO] ScreenCaptor health check…
2024-02-22 00:14:30.343 [INFO] Recorder health check…
2024-02-22 00:14:31.247 [INFO] ScreenCaptor health check…
2024-02-22 00:14:31.359 [INFO] Recorder health check…
2024-02-22 00:14:32.247 [INFO] ScreenCaptor health check…
2024-02-22 00:14:32.361 [INFO] Recorder health check…
2024-02-22 00:14:33.263 [INFO] ScreenCaptor health check…
2024-02-22 00:14:33.373 [INFO] Recorder health check…
2024-02-22 00:14:34.281 [INFO] ScreenCaptor health check…
2024-02-22 00:14:34.378 [INFO] Recorder health check…
2024-02-22 00:14:35.297 [INFO] ScreenCaptor health check…
2024-02-22 00:14:35.395 [INFO] Recorder health check…
2024-02-22 00:14:36.297 [INFO] ScreenCaptor health check…
2024-02-22 00:14:36.408 [INFO] Recorder health check…
2024-02-22 00:14:37.313 [INFO] ScreenCaptor health check…
2024-02-22 00:14:37.408 [INFO] Recorder health check…
2024-02-22 00:14:38.313 [INFO] ScreenCaptor health check…
2024-02-22 00:14:38.411 [INFO] Recorder health check…
2024-02-22 00:14:38.560 [EVENT] Pressed ⌘S hotkey associated with StopRecordingSessionCommand command.
2024-02-22 00:14:38.560 [INFO] Screen recording session changed state: recording → finishing.
2024-02-22 00:14:38.560 [INFO] Recorder updating state from: recording, to: finishing
2024-02-22 00:14:38.560 [INFO] AssetInput changed writable state to: false
2024-02-22 00:14:38.561 [INFO] ScreenCaptor stopping capturing, current state: capturing
2024-02-22 00:14:38.561 [INFO] ScreenLink stopping display link…
2024-02-22 00:14:38.562 [INFO] Recorder updating state from: finishing, to: finished
2024-02-22 00:14:38.562 [INFO] ScreenLink updating state from: running, to: idle
2024-02-22 00:14:38.562 [INFO] ScreenCaptor synchronizing with screen link state from: capturing, to: idle
2024-02-22 00:14:38.562 [WARN] Sample pts: 14.317 couldn't be written into Media.AssetWriter as it's already terminated with state: finished
2024-02-22 00:14:38.564 [INFO] Disabling ⌘S shortcut associated with StopRecordingSessionCommand command.
2024-02-22 00:14:38.564 [INFO] Accessing output directory url: /Users/dword/Downloads.
2024-02-22 00:14:38.567 [INFO] Screen recording session changed state: finishing → finished.
2024-02-22 00:14:38.775 [INFO] Accessing output directory url: /Users/dword/Downloads.
2024-02-22 00:14:38.775 [DEBUG] Starting queued Gifox.MediaExportTask task…
2024-02-22 00:14:38.780 [INFO] Exporting document composition: Composition(size: <w:774.0 h:497.0>, fps: 20.0, duration: 14.31667, tracks: 1 [0.0:14.31667], storylines: 1  [0.0:14.31667])
2024-02-22 00:14:38.781 [INFO] Setting up palette transcoder with configuration: Configuration(size: <w:1548 h:994>, colors: 192)
2024-02-22 00:14:42.014 [DEBUG] Request is waiting for 10 ms…
[Parsed_palettegen_0 @ 0x600000cd2470] 192 colors generated out of 100136 colors; ratio=0.001917
[Parsed_palettegen_0 @ 0x600000cd2470] Duped color: FF2D2629
[image2 @ 0x117fadcd0] The specified filename '/var/folders/yt/mkzzc_lj5wvbcvfgptg9vg7w0000gn/T/com.gifox.gifox2-appstore/Gifox 2/Palette/C6BE6697-53B6-4114-964A-8390F9003560.png' does not contain an image sequence pattern or a pattern is invalid.
[image2 @ 0x117fadcd0] Use a pattern such as %03d for an image sequence or use the -update option (with -frames:v 1 if needed) to write a single image.
2024-02-22 00:14:42.049 [INFO] Palette transcoder did terminate with state: finished
2024-02-22 00:14:42.050 [INFO] System: MacBookAir10,1 Version 13.4 (Build 22F66), Memory: 373.9 MB (16.0 GB), Processor: Apple M1: 69.1% (10.2%), GPU: Apple M1, Display: <"Built-in Retina Display" main: true, scale: 2.0, frame: (0.0, 0.0, 1440.0, 900.0), bounds: (0.0, 0.0, 1440.0, 900.0), color space: "Color LCD colorspace", refresh rate: "60.0 Hz">, Power: <"InternalBattery-0" capacity: 82%, charging: false, charged: false>
2024-02-22 00:14:42.050 [INFO] Setting up GIF transcoder with configuration: Configuration(size: <w:1548 h:994>, colors: 192, pal. mode: global, dither: bayer, repeats: ∞, pause: 0.0s)
2024-02-22 00:14:43.354 [INFO] Removed 1 media item(s).
2024-02-22 00:14:46.297 [DEBUG] Request is waiting for 10 ms…
2024-02-22 00:14:46.308 [INFO] GIF transcoder did terminate with state: finished
2024-02-22 00:14:46.309 [INFO] System: MacBookAir10,1 Version 13.4 (Build 22F66), Memory: 368.3 MB (16.0 GB), Processor: Apple M1: 137.5% (10.2%), GPU: Apple M1, Display: <"Built-in Retina Display" main: true, scale: 2.0, frame: (0.0, 0.0, 1440.0, 900.0), bounds: (0.0, 0.0, 1440.0, 900.0), color space: "Color LCD colorspace", refresh rate: "60.0 Hz">, Power: <"InternalBattery-0" capacity: 82%, charging: false, charged: false>
2024-02-22 00:14:46.310 [INFO] Accessing output directory url: /Users/dword/Downloads.
2024-02-22 00:14:46.313 [DEBUG] Completed Gifox.MediaExportTask task
2024-02-22 00:16:28.331 [INFO] Accessing output directory url: /Users/dword/Downloads.
2024-02-22 00:16:28.333 [DEBUG] Starting queued Gifox.MediaExportTask task…
2024-02-22 00:16:28.333 [INFO] Exporting document composition: Composition(size: <w:774.0 h:497.0>, fps: 20.0, duration: 4.9, tracks: 2 [0.0:1.90993, 1.90993:4.9], storylines: 1  [0.0:4.9])
2024-02-22 00:16:28.334 [INFO] Setting up palette transcoder with configuration: Configuration(size: <w:1548 h:994>, colors: 192)
2024-02-22 00:16:30.143 [DEBUG] Request is waiting for 10 ms…
[Parsed_palettegen_0 @ 0x600000cd3910] 192 colors generated out of 89679 colors; ratio=0.002141
[Parsed_palettegen_0 @ 0x600000cd3910] Duped color: FF363032
[image2 @ 0x150835ea0] The specified filename '/var/folders/yt/mkzzc_lj5wvbcvfgptg9vg7w0000gn/T/com.gifox.gifox2-appstore/Gifox 2/Palette/25161787-3777-42ED-B069-A9A3829DB84B.png' does not contain an image sequence pattern or a pattern is invalid.
[image2 @ 0x150835ea0] Use a pattern such as %03d for an image sequence or use the -update option (with -frames:v 1 if needed) to write a single image.
2024-02-22 00:16:30.172 [INFO] Palette transcoder did terminate with state: finished
2024-02-22 00:16:30.172 [INFO] System: MacBookAir10,1 Version 13.4 (Build 22F66), Memory: 381.1 MB (16.0 GB), Processor: Apple M1: 50.4% (10.2%), GPU: Apple M1, Display: <"Built-in Retina Display" main: true, scale: 2.0, frame: (0.0, 0.0, 1440.0, 900.0), bounds: (0.0, 0.0, 1440.0, 900.0), color space: "Color LCD colorspace", refresh rate: "60.0 Hz">, Power: <"InternalBattery-0" capacity: 82%, charging: false, charged: false>
2024-02-22 00:16:30.172 [INFO] Setting up GIF transcoder with configuration: Configuration(size: <w:1548 h:994>, colors: 192, pal. mode: global, dither: bayer, repeats: ∞, pause: 0.0s)
2024-02-22 00:16:32.495 [DEBUG] Request is waiting for 10 ms…
2024-02-22 00:16:32.506 [INFO] GIF transcoder did terminate with state: finished
2024-02-22 00:16:32.506 [INFO] System: MacBookAir10,1 Version 13.4 (Build 22F66), Memory: 468.8 MB (16.0 GB), Processor: Apple M1: 133.7% (10.2%), GPU: Apple M1, Display: <"Built-in Retina Display" main: true, scale: 2.0, frame: (0.0, 0.0, 1440.0, 900.0), bounds: (0.0, 0.0, 1440.0, 900.0), color space: "Color LCD colorspace", refresh rate: "60.0 Hz">, Power: <"InternalBattery-0" capacity: 82%, charging: false, charged: false>
2024-02-22 00:16:32.507 [INFO] Accessing output directory url: /Users/dword/Downloads.
2024-02-22 00:16:32.508 [DEBUG] Completed Gifox.MediaExportTask task
2024-02-22 00:16:33.233 [INFO] Accessing output directory url: /Users/dword/Downloads.
2024-02-22 00:16:58.667 [EVENT] Pressed menu button in library view.
```


Do you need any additional info?

**Comment by iby** [comment] 2024-02-22 19:43
Hey @stdword! Thanks for the detailed logs and some context. We had a closer look and confirmed a couple of issues. Will get this fixed in the upcoming update! Again, thanks for the report! ❤️‍🔥

**Comment by iby** [comment] 2024-03-21 19:58
Hello everyone! Sorry for going off the radar in the past few weeks. We just released a 2.6.4 update addressing this and a few other related issues, can you please get the latest version and let me know if there is anything else odd going on? 🙏

**Closed as completed by iby** 2024-03-21 19:58 UTC
Labels: bug, frontlog

**Comment by stdword** [comment] 2024-03-21 21:25
@iby Hello! Thank you! I'll check it when app updates to new version.

This is strange, but I cannot update it manually — the update button has disappeared 🤷‍♂️
<img width="400px" src="https://github.com/Gifox/Tracker/assets/1984175/df0c5923-ddc4-496a-8b73-a8c79ac03e2b"/>

**Comment by iby** [comment] 2024-03-22 10:32
@stdword there's no "manual" update in Mac App Store and Setapp versions – I'm guessing you've got the app from there and that's the reason why you're not seeing it. If that's the case, please check for updates in App Store or Setapp – the latest version is available there too! 👍

**Comment by stdword** [comment] 2024-03-22 16:59
Oh! Yeah! I have just updated and testsed the new version — it works perfect! This issue is resolved 🙏 ❤️
