### ISSUE TITLE
Play in edit mode does not work

### ISSUE THREAD

**Issue by xmoner** [Gifox/Tracker#198] opened 2021-07-24 07:27 UTC
After cutting some frames and remove some of them, the button Play does not work.

**Comment by tgrosinger** [comment] 2021-07-31 16:20
I am also experiencing this in 2.2.5 installed via MacApp store. Same problem when installed from SetApp.

**Comment by tgrosinger** [comment] 2021-07-31 16:22
I think this is a duplicate of #192

**Comment by iby** [comment] 2022-06-18 09:14
It feels that way indeed, thanks for pointing out @tgrosinger. Going to close this in favour of #182 as we got a lot more info in there! Thanks everyone! 🙏

**Closed by iby** 2022-06-18 09:14 UTC
