### ISSUE TITLE
Keyboard capture not working

### ISSUE THREAD

**Issue by Nigelw** [Gifox/Tracker#120] opened 2019-11-28 03:47 UTC
Congrats on the v2 release! Following up on an [issue I reported a few months back during the v2 beta](https://github.com/Gifox/Tracker/issues/27#issuecomment-507886374).

Keyboard interaction still isn't being captured in the v2.0.0 release. I'm currently testing this on a 2019 MacBook Air (retina display) running macOS 10.14.6.

Let me know if you'd like me to help track this down. I'm happy to provide logs or anything else that may shed light on the issue.

**Comment by ianbytchek** [comment] 2019-11-28 07:53
Thank you! Yes, logs would be very useful. Not sure what happened with the logs you've sent back in July, but I can't see them at my end… very strange. So, yes please. Can you confirm if both keyboard and mouse interactions are not being captured or if the issue is only with the keyboard?

**Comment by Nigelw** [comment] 2019-11-28 08:40
Confirmed that mouse interactions are captured fine. It's only keyboard which isn't being recorded.

Just sent logs via in-app feedback running on a 2014 non-retina MBA. Seeing the same issue as on the 2019 retina MBA I tested on earlier.

**Comment by ianbytchek** [comment] 2019-11-29 09:39
Just to give the heads up, the issue was reproduced at our end and the fix is on the way.

**Comment by Nigelw** [comment] 2019-11-29 09:57
Great! Thanks for the update and figuring out a fix so quickly.

**Comment by ianbytchek** [comment] 2019-11-30 16:03
![2019-11-30 16 01 38](https://user-images.githubusercontent.com/1086845/69902912-c9c88e00-138a-11ea-82df-9a4b86126294.gif)

Apparently there was another Catalina gotcha that we missed. Will be released in a day or two! 👍

**Closed** 2019-11-30 17:18 UTC
