### ISSUE TITLE
Mouse interactions are not being captured

### ISSUE THREAD

**Issue by cconnis** [gifox/tracker#266] opened 2023-10-04 22:44 UTC
Mouse interactions/clicks are not being captured with either the window or free area selection options. Attached are examples of each and my diagnostic data.

Thanks!
![selection](https://github.com/Gifox/Tracker/assets/17502366/9b03795e-5a6b-45bb-9aa2-ee20022b25e8)
![window](https://github.com/Gifox/Tracker/assets/17502366/81bfa377-efb4-4700-9e53-858921777e59)
[App Logs.txt](https://github.com/Gifox/Tracker/files/12810133/App.Logs.txt)
[App Settings.txt](https://github.com/Gifox/Tracker/files/12810134/App.Settings.txt)
[System Info.txt](https://github.com/Gifox/Tracker/files/12810135/System.Info.txt)

**Comment by iby** [comment] 2023-10-05 13:49
Thanks for reporting this. I checked out the logs, nothing immediate stands out… 🤔 Can you please check if keyboard interactions are getting captured? I can see from the logs you have quite a few recordings. Is this a recent happening? Any hardware changes? Trying to put pieces together and figure out what might be going wrong… Thanks for any input! 🙏

**Comment by cconnis** [comment] 2023-10-05 15:42
Hey Ian, keyboard interactions are being captured, and yes this is quite recent. I haven't had any recent hardware changes, but I did update to macOS Sonoma recently and am on version 14.0. I bet that's it!

**Comment by iby** [comment] 2023-10-07 09:20
Hey Casey, thanks again for reporting this and the details. The issues seems to be related to Sonoma and related to animation rendering. We missed it during testing – it does work with glitches with a different degree of success. We'll be releasing and update next week and will address this issue. Will update this thread with further news, stay tuned! 🙏

**Comment by cconnis** [comment] 2023-10-09 15:39
Awesome, thank you!

**Comment by o1y** [comment] 2023-10-30 10:10
Hey, I'm having the same issue since I've been on Sonoma 14.0 and 14.1. Mouse interactions and keyboard interactions aren't being captured or only work for just half a second.

![2023-10-30 11 07 46](https://github.com/Gifox/Tracker/assets/1102712/53cfd9b7-2fc5-4651-b58d-6a64f0690aff)

**Comment by iby** [comment] 2023-11-09 13:33
Hey friends! A quick update, we released 2.6.2 but didn't find a workaround for this particular issue. We'll be releasing a Beta version next week in attempt to find a fix for this and #267. I'll post here with further updates. Apologies for the troubles… 😔

**Comment by iby** [comment] 2023-11-28 11:51
Hello, a quick update. We pinpointed the issue, it's linked to internal changes in Sonoma related to drawing (optimizations, presumably). I'm looking into possible workarounds, hoping to release a fix in the upcoming Beta later this week.

**Comment by iby** [comment] 2023-12-07 15:07
Howdy friends! The new Beta has just been published, it comes with a few improvements and addresses glitchy mouse interaction capture. If you can give it a go and report any issues, would be much appreciated! 🙏

P. S. [Here's](https://github.com/Gifox/Tracker/issues/267#issuecomment-1824966959) how to enable pre-releases or download directly from our website.

**Comment by o1y** [comment] 2023-12-12 11:04
Great, that fixes this issue, thanks so much! :)

**Comment by iby** [comment] 2023-12-21 12:41
Everyone, thanks for the feedback and patience! Based on the Beta comments and discussions it seems the issue is resolved. Version 2.6.3 was released yesterday – please get the update. If you're still running into any troubles, please do let me know? 👍🙏

**Closed as completed by iby** 2023-12-21 12:41 UTC
Labels: bug, frontlog
