### ISSUE TITLE
Option to run Gifox as a dock-app rather than a menu item

### ISSUE THREAD

**Issue by stuwillis** [Gifox/Tracker#103] opened 2018-10-15 11:08 UTC
Even with Bartender I am running out of space in my menubar for all these apps. Apps like PasteBot and Alfred let me run with a dock app. Thanks.

**Comment by ianbytchek** [comment] 2019-12-15 11:44
Duplicate of #1. This is planned, but no ETA yet, keep an eye on the original issue.

**Closed by ianbytchek** 2019-12-15 11:44 UTC
